import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {Providers} from './providers'
import './globals.css'
import Header from '@/components/header'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className="light">
      <body className={`${inter.className} container mx-auto`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
